### PR TITLE
Promote PropertyUtils from gradle-commons-test

### PR DESCRIPTION
**Pull request by Azurelol**
## Description

Adds PropertyUtils from gradle-commons-test and a newer static constructor in PropertyLookup that composes the environment key from the property key name.

- PropertyUtils is quite useful and can be used by more than test classes
- The newer static constructor for PropertyLookup uses a PropertyUtils method that follows convention

## Changes
* ![ADD] PropertyUtils
* ![UPDATE] PropertyLookup

[NEW]:      https://resources.atlas.wooga.com/icons/icon_new.svg "New"
[ADD]:      https://resources.atlas.wooga.com/icons/icon_add.svg "Add"
[IMPROVE]:  https://resources.atlas.wooga.com/icons/icon_improve.svg "Improve"
[CHANGE]:   https://resources.atlas.wooga.com/icons/icon_change.svg "Change"
[FIX]:      https://resources.atlas.wooga.com/icons/icon_fix.svg "Fix"
[UPDATE]:   https://resources.atlas.wooga.com/icons/icon_update.svg "Update"
[BREAK]:    https://resources.atlas.wooga.com/icons/icon_break.svg "Remove"
[REMOVE]:   https://resources.atlas.wooga.com/icons/icon_remove.svg "Remove"
[IOS]:      https://resources.atlas.wooga.com/icons/icon_iOS.svg "iOS"
[ANDROID]:  https://resources.atlas.wooga.com/icons/icon_android.svg "Android"
[WEBGL]:    https://resources.atlas.wooga.com/icons/icon_webGL.svg "WebGL"
[GRADLE]:   https://resources.atlas.wooga.com/icons/icon_gradle.svg "GRADLE"
[UNITY]:    https://resources.atlas.wooga.com/icons/icon_unity.svg "Unity"
[LINUX]:    https://resources.atlas.wooga.com/icons/icon_linux.svg "Linux"
[WIN]:      https://resources.atlas.wooga.com/icons/icon_windows.svg "Windows"
[MACOS]:    https://resources.atlas.wooga.com/icons/icon_iOS.svg "macOS"

### CODE REVIEW

**Review by Larusso — CHANGES_REQUESTED** [review]
Can you please add in the description the reason `why` it was taken from commons-test?

Also could you please not add changes for a totally different class?
I see both additions and tests for `PropertyLookup` class which where not mentioned in the PR description.

**Comment by Azurelol** [comment]
> Can you please add in the description the reason `why` it was taken from commons-test?
> 
> Also could you please not add changes for a totally different class? I see both additions and tests for `PropertyLookup` class which where not mentioned in the PR description.

Sure.

One of the reasons I added the CTOR there was to provide a direct use case for the class being added, as well because I would like to use it in atlas-unity:

image

**Comment by Larusso** [comment]
@Azurelol the overall direction of changes should not span over multiple repos into a single patch. If the patch says it adds A and does also B and C just for convinience. That should either be directly reflected in the patch description or be added as yet another patch. Also, this is a common library. There is no need to add usecases for classes. It should be assumed that classes added to a libary have a reason to be added :).

**Comment by Azurelol** [comment]
I will open another PR for the new method for PropertyLookup.

**Pull request merged**
